# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import pinboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style_color', models.CharField(blank=True, default=pinboard.models.get_color, max_length=50)),
                ('style_transform_range', models.IntegerField(blank=True, default=pinboard.models.get_range)),
                ('style_font', models.CharField(blank=True, default=pinboard.models.get_font, max_length=50)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pin',
            name='tag',
            field=models.ManyToManyField(blank=True, to='pinboard.Tag'),
        ),
    ]
