# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0002_auto_20170905_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='body',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='title',
        ),
        migrations.AlterField(
            model_name='pin',
            name='tag',
            field=models.ManyToManyField(blank=True, to='pinboard.Tag'),
        ),
    ]
