# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0003_auto_20170905_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default=b'white', max_length=50)),
                ('transform_range', models.PositiveIntegerField(default=-2)),
                ('font', models.CharField(blank=True, default=b'kalpurush', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pin',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='pin',
            name='style',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinboard.Style'),
        ),
    ]
