# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0004_auto_20170905_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='color',
            field=models.CharField(blank=True, default=b'blue', max_length=50),
        ),
        migrations.AlterField(
            model_name='style',
            name='transform_range',
            field=models.PositiveIntegerField(default=-3),
        ),
    ]
