# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0005_auto_20170905_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='color',
            field=models.CharField(blank=True, default=b'white', max_length=50),
        ),
    ]
