# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0006_auto_20170905_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='style',
        ),
        migrations.AddField(
            model_name='pin',
            name='style_color',
            field=models.CharField(blank=True, default=b'yellow', max_length=50),
        ),
        migrations.AddField(
            model_name='pin',
            name='style_font',
            field=models.CharField(blank=True, default=b'kalpurush', max_length=50),
        ),
        migrations.AddField(
            model_name='pin',
            name='style_transform_range',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
