# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import pinboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0007_auto_20170905_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='style_color',
            field=models.CharField(blank=True, default=pinboard.models.get_color, max_length=50),
        ),
        migrations.AlterField(
            model_name='pin',
            name='style_font',
            field=models.CharField(blank=True, default=pinboard.models.get_font, max_length=50),
        ),
        migrations.AlterField(
            model_name='pin',
            name='style_transform_range',
            field=models.PositiveIntegerField(blank=True, default=pinboard.models.get_range),
        ),
    ]
