# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0008_auto_20170905_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='text',
            field=models.TextField(),
        ),
    ]
